version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./pastel360-api:/var/www/html
      - ./docker/extensions/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./logs/xdebug:/var/log
    environment:
      - XDEBUG_MODE=coverage
      - XDEBUG_CONFIG="client_host=host.docker.internal"
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    depends_on:
      - sonarqube
      - postgresql
    networks:
      - net

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - '80:80'
    volumes:
      - ./pastel360-api:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - net

  postgresql:
    image: postgres:15
    container_name: postgresql
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: database
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - net

  sonarsql:
    image: postgres:15
    container_name: sonarsql
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: sonarqube
      POSTGRES_PASSWORD: sonarpass
      POSTGRES_DB: sonar
    volumes:
      - sonarsql_data:/var/lib/postgresql/data
    networks:
      - net

  sonarqube:
    image: sonarqube:10-community
    ports:
      - '9999:9000'
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://sonarsql:5432/sonar
      SONAR_JDBC_USERNAME: sonarqube
      SONAR_JDBC_PASSWORD: sonarpass
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions
    depends_on:
      - sonarsql
    networks:
      - net

networks:
  net:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions:
  sonarsql_data:
  postgresql_data:
